config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trips do
    resources :events
    resources :venues
  end
end

app/views/shared/_banner.html.erb
  <div class="banner" style="background-image:
  linear-gradient(-225deg, rgba(186,210,213,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'dawn-dusk.jpg' %>);">
  <div class="banner-content">
    <div class="first-title">
      <p>
      </p>
      <h2>Experience
        <span id="banner-typed-text"></span>
      </h2>
      <h4>One Trip At a Time</h4>
    </div>
    <div class="form">
      <div class="simple-form form-inline">
        <div class="form-box">
          <%= simple_form_for @trip, url: trips_path, method: :post do |f| %>
          <%= f.input :city, label: false, placeholder: "Destination", input_html:{class: "city-input"} %>
          <%= f.input :start_day,label: false, as: :string, placeholder: "Start date", required: true, input_html: {class: "datepicker date-input", id: "start-date"} %>
          <%= f.input :end_day,label: false, as: :string, placeholder: "End date", required: true, input_html: {class: "datepicker date-input", id: "end-date"} %>
          <%= f.submit 'Explore', class: "btn home-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<%= icon("fas", "chevron-down") %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_home_description.erb
<div class="description-wrapper">

  <div class="sect sect--type">
    <div class="container">
      <div class="row row--center">
        <div class="col-md-5 col-xs-8 col-sm-6 col--inbl">
          <h2 class="sect__title">How it works</h2>

        </div>
      </div>
      <div class="row row--small row--margin row--center">
        <div class="col-md-4 col-sm-4 steps">
          <img src="https://res.cloudinary.com/druzius/image/upload/v1543516647/map-of-roads_1.png" class="steps__img">
          <h2 class="steps__name">SELECT YOUR DESTINATION</h2>
          <p class="steps__descr">
            A location close to adrenaline, chill out, or local culture - your choice. It all depends on your travel style, so follow your heart.
          </p>
        </div>


        <div class="col-md-4 col-sm-4 steps">
          <img src="https://res.cloudinary.com/druzius/image/upload/v1543520948/feedback.png" class="steps__img">
          <h2 class="steps__name">TELL US ABOUT YOURSELF</h2>
          <p class="steps__descr">
            Let us understand you a little better by filling up your preference form and a personalized itinerary will be generated.
          </p>
        </div>

         <div class="col-md-4 col-sm-4 steps">
          <img src="https://res.cloudinary.com/druzius/image/upload/v1543521099/destination.png" class="steps__img">
          <h2 class="steps__name">GET A FULL ITINERARY</h2>
          <p class="steps__descr">
            Adjust the generated itinerary as you wish and manage it whenever you want from your personal dashboard.
          </p>
        </div>
      </div>

    </div>
  </div>

  <div class="sect sect--great">
    <div class="container">
      <div class="row">
        <div class="col-md-5 col-sm-7 col-sm-offset-4 col-md-offset-6">
          <div class="description">
        <h2 class="description__title">SEE & DO MORE</h2>
        <p class="description__p">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
        <a href="#top" class="btn home-button">Explore</a>
        </div>
        </div>
      </div>
    </div>
  </div>

  <div class="half-sect">
    <div class="half half-sect__first">
      <div class="description">
        <h2 class="description__title">EASILY MEET OTHER TREEPSTERS</h2>
        <p class="description__p">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
        <a href="#top" class="btn home-button">Explore</a>
      </div>

    </div>
      <div class="half half-sect__second">  </div>
  </div>

  <div class="sect sect--best sect--center">
    <div class="container">



          <h2 class="sect__title best--bottom sect--white-text">What other treepsters say</h2>
        <div class="cards">

            <figure class="snip1515">
              <div class="profile-image"><img src="https://res.cloudinary.com/druzius/image/upload/v1543511876/norman-toth-177973-unsplash.jpg" alt="sample47" /></div>
              <figcaption>
                <h3>Fleece Marigold</h3>
                <h4>Vird Retailer</h4>
                <p>I booked a last minute flight to Helsinki and ended up ice swimming and dog sledding!</p>

              </figcaption>
            </figure>

                          <figure class="snip1515">
              <div class="profile-image"><img src="https://res.cloudinary.com/druzius/image/upload/v1543512866/hector-martinez-108947-unsplash.jpg" alt="sample83" /></div>
              <figcaption>
                <h3>Ruby Von Rails</h3>
                <h4>Web Designer</h4>
                <p>I'm killing time while I wait for life to shower me with meaning and happiness.</p>

              </figcaption>
            </figure>


                          <figure class="snip1515">
              <div class="profile-image"><img src="https://res.cloudinary.com/druzius/image/upload/v1543512979/clem-onojeghuo-171672-unsplash.jpg" alt="sample83" /></div>
              <figcaption>
                <h3>Ben Franklin</h3>
                <h4>Photographer</h4>
                <p>I travel the world and try to catch the best images, but never have much time to plan fun stuff.</p>

              </figcaption>
            </figure>

        </div>

        <p class="sect__subtitle best--margin sect--white-text ">
          Follow in their footsteps and don't worry about planning activities and searching for the best places to grab a steps.<br> Don't want to miss that concert you heard of, but can't find the venue?<br>Don't have time to look for a restaurant with your favorite food?</p>
          <p class="sect__subtitle best--margin sect--white-text "><strong>We do it for you!</strong></p>

          <a href="#top" class="btn home-button">Explore</a>


    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-static-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My Trips", trips_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link", remote: true %>
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link", remote: true %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>