config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trips do
    resources :events
    resources :venues
  end
end

app/models/event.rb
class Event < ApplicationRecord
  EVENT_CARD_IMAGES = {
   "103" => 'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933435/music.jpg',
   "101" => 'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933434/business.jpg',
   "104" => 'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933437/film-media.jpg',
   "102" => 'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543935226/science-tech.jpg'
  }

  EVENTBRITE_SUB_CATEGORY_IMAGES = {
    "3002" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543932418/jazz-blues.jpg",
    "3003" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543932416/classical.jpg",
    "3006" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543932420/electronic.jpg",
    "3008" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543932419/hiphop-rap.jpg",
    "1001" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933429/start-up.jpg",
    "1002" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933430/finance.jpg",
    "1007" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933430/real-estate.jpg",
    "1005" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543933438/sales-marketing.jpg",
    "4004" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543935036/gaming.jpg",
    "4003" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934741/anime.jpg",
    "4002" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934745/film.jpg",
    "4005" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934741/comics.jpg",
    "2001" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934738/medicine.jpg",
    "2002" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934740/science.jpg",
    "2003" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934737/Biotech.jpg",
    "2004" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543934742/hightech.jpg"
  }
  belongs_to :trip
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper
  def index
    @trip = Trip.find(params[:trip_id])
    @eventbrite_main_categories = ["Music", "Business", "Film & Media", "Science & Tech"]
    @eventbrite_sub_categories = eventbrite_sub_categories
  end

  def create
    @eventbrite_sub_categories = eventbrite_sub_categories
    @trip = Trip.find(params[:trip_id])
    @latitude = @trip.latitude
    @longitude = @trip.longitude

    @start_day = @trip.start_day
    @formatted_start = @start_day.strftime('%Y-%m-%dT%H:%M:%S')
    @end_day = @trip.end_day
    @formatted_end = @end_day.strftime('%Y-%m-%dT%H:%M:%S')

    if !params["sub_category"]["choices"].drop(1).nil?
      @chosen_categories = params["sub_category"]["choices"].drop(1)
      @chosen_categories.each do |category, values|
        @result = eventbrite_api(@latitude, @longitude, @formatted_start, @formatted_end, @eventbrite_sub_categories[category][0], @eventbrite_sub_categories[category][1])

        if !@result.nil?
          @result.first(2).each do |event|
            @event = Event.new(name: event[:name], latitude: event[:latitude], longitude: event[:longitude], event_start: event[:event_start], event_end: event[:event_end], trip_id: @trip.id, img_url: Event::EVENTBRITE_SUB_CATEGORY_IMAGES[event[:sub_category]])
            @event.save
          end
        end
      end
    end
    respond_to do |format|
      format.html { redirect_to trip_venues_path }
      format.js
    end
  end
end

app/views/events/index.html.erb
<div class="bg-image-wrapper" style="background-image:
linear-gradient(-225deg, rgba(186,210,213,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://res.cloudinary.com/druzius/image/upload/v1543828892/emanuel-hahn-200491-unsplash.jpg');">
  <div class="container">
    <div class="show-category-title">
      <div class="title-bg text-center">
        <h2>Explore Events Happening in <%= @trip.city.capitalize %> !</h2>
        <h4>Choose Your Preferences From Each Category</h4>
      </div>
    </div>
    <div class="show-category-card-sect">
      <div class="row">
        <% i = 0 %>
        <% @eventbrite_main_categories.each_with_index do |cat, index| %>
          <div class="col-xs-12 col-lg-3">
            <div class="show-category-card">
              <div class="menu-button show-category-card-image">
                <%= cl_image_tag(Event::EVENT_CARD_IMAGES[index]) %>
                <div class="show-category-card-caption"><%= cat %></div>
              </div>
              <div class="menu hide-start">
                <%= simple_form_for :sub_category, remote: true, url: trip_events_path(@trip), method: :post do |f| %>
                  <%= f.input :choices, as: :check_boxes, collection: @eventbrite_sub_categories.keys[i..i+3]%>
                  <div class="submit-category-button">
                    <%= f.submit "Next", class: "btn home-button submit-venue-category" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <% i = i + 4 %>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="button-to-events">
          <%= link_to trip_path(@trip) do %>
            <div class="to-events btn home-button">GENERATE YOUR TRIP >></div>
          <% end %>
          </div>
        </div>
      </div>
<script>
  const bigButtons = document.querySelectorAll('.menu-button');
  const row_of_menus = document.querySelector('.row');
  let first_menu = row_of_menus.firstElementChild;
  first_menu= first_menu.querySelector('.menu');
  first_menu.classList.remove('hide-start');

  bigButtons.forEach((bigButton) => {
    bigButton.addEventListener('click', function(event) {
      let menu = bigButton.nextElementSibling;
      menu.classList.toggle("hide-start");
      let submit = menu.querySelector('.submit-venue-category');
      submit.addEventListener("click", function(event){
        // console.log("bigButton baby");
        // console.log(bigButton.parentNode);
        // console.log(bigButton.parentNode.parentNode.nextElementSibling.firstElementChild);
        let next_guy = bigButton.parentNode.parentNode.nextElementSibling.firstElementChild;
        let next_menu = next_guy.querySelector('.menu');
        next_menu.classList.remove('hide-start');
        menu.classList.add('hide-start');
      })
    });
  });

  let submits = document.querySelectorAll(".submit-venue-category");
  submits.forEach((submit) => {
  submit.addEventListener('click', function(event){

    // console.log(submit.parentNode.parentNode.nextElementSibling.firstElementChild);
    console.log("small button, size doesn't matter");
    // console.log(submit.parentNode.parentNode.parentNode.parentNode.parentNode.nextElementSibling.firstElementChild);
    let next_guy = submit.parentNode.parentNode.parentNode.parentNode.parentNode.nextElementSibling.firstElementChild;
    let next_menu = next_guy.querySelector('.menu');
    next_menu.classList.remove('hide-start');

    console.log(submit.parentNode.parentNode.parentNode);
    let current_menu = submit.parentNode.parentNode.parentNode;
    current_menu.classList.add('hide-start');
  });
  });
</script>

app/views/events/new.html.erb
<div class="image-wrapper" style="background-image:
linear-gradient(-225deg, rgba(186,210,213,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'beach-car.jpg' %>);">
<div class="container">
  <div class="header">
    <div class="header text-center">
      <h1>Event type</h1>
      <h4>Which music events are to your likeing?</h4>
    </div>
  </div>

  <div class="venue-category-cards">
    <div class="row">
      <% @events.each do |event| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
          <div class="card-category"><%= event["name"]["text"] %></div>
          <div class="card-description">
            <h2><%= event[:address] %></h2>
          </div>
        </div>
        <div class="confirm-selection text-center">
          <a href="#" class="btn btn-primary">select</a>
          <a href="#" class="btn btn-danger">shuffle</a>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>
</div>