config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trips do
    resources :events
    resources :venues
  end
end

app/models/venue.rb
class Venue < ApplicationRecord

  VENUE_CARD_IMAGES = ['https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_2260/v1543755687/pooja-chaudhary-633059-unsplash.jpg',
                       'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1688/v1543755688/alexander-popov-522100-unsplash.jpg',
                       'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1763/v1543769862/ancient-ancient-civilization-arch-159862.jpg',
                     'https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1377/v1543755693/jared-rice-389056-unsplash.jpg']

  FOURSQUARE_CATEGORY_IMAGES = {
  "4bf58dd8d48988d16c941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1683/v1543930000/burger.jpg",
  "4bf58dd8d48988d145941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1593/v1543930137/asian.jpg",
  "58daa1558bbb0b01f18ec1cd" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543930000/middle-eastern.jpg",
  "4bf58dd8d48988d110941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1572/v1543929998/italian.jpg",
  "4bf58dd8d48988d11e941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1626/v1543930002/pub.jpg",
  "4bf58dd8d48988d11f941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1526/v1543929998/club.jpg",
  "4bf58dd8d48988d120941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1572/v1543930001/other-nightlife.jpg",
  "53e510b7498ebcb1801b55d4" => "https://res.cloudinary.com/druzius/image/upload/q_auto:eco/v1543929997/nightmarket.jpg",
  "4bf58dd8d48988d1e2931735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543929999/art-gallery.jpg",
  "4deefb944765f83613cdba6e" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1563/v1543929999/historic-site.jpg",
  "52e81612bcbc57f1066b79ee" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1674/v1543769209/timon-klauser-308449-unsplash.jpg",
  "4bf58dd8d48988d137941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1491/v1543930951/theater.jpg",
  "52e81612bcbc57f1066b7a21" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1780/v1543930953/national-parks.jpg",
  "4bf58dd8d48988d159941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1505/v1543930952/trail.jpg",
  "4bf58dd8d48988d176941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1568/v1543930952/gym.jpg",
  "4bf58dd8d48988d165941735" => "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1545/v1543930950/scenic-lookout.jpg"
  }

  GENERIC_VENUE_IMAGE = "https://res.cloudinary.com/druzius/image/upload/c_scale,q_auto:eco,w_1675/v1544037459/camera-destination-finger-7979.jpg"
  belongs_to :trip
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  include ApplicationHelper
  def index
    @trip = Trip.find(params[:trip_id])
    @foursquare_sub_categories = FoursquareCategory.all
    @foursquare_main_categories = ["Food", "Nightlife", "culture", "outdoors"]
  end

  def new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @location = @trip.city
    @price = 2
    if !params["sub_category"]["choices"].drop(1).nil?
      @chosen_categories = params["sub_category"]["choices"].drop(1)
      @chosen_categories.each do |category|
        @result = foursquare_api(FoursquareCategory.find(category).category_id, @location)
        if !@result.nil?
          @result.first(2).each do |venue|
            details = venue_details_api(venue[:venue_id])
            @venue = Venue.new(name: venue[:name], location: venue[:address], trip_id: @trip.id, img_url: Venue::FOURSQUARE_CATEGORY_IMAGES[venue[:category_id]], description: details[:description], facebook: details[:facebook], phone: details[:phone], instagram: details[:instagram], category_tag: details[:category_tag], price_tier: details[:price_tier], likes: details[:likes], rating: details[:rating])
            @venue.img_url = Venue::GENERIC_VENUE_IMAGE if @venue.img_url.nil?
            @venue.save
          end
        end
      end
    end
    # respond_to do |format|
    #   format.html { redirect_to trip_venues_path }
    #   format.js
    # end
  end
end

app/views/venues/index.html.erb
<div class="bg-image-wrapper" style="background-image:
linear-gradient(-225deg, rgba(186,210,213,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://res.cloudinary.com/druzius/image/upload/v1543828892/emanuel-hahn-200491-unsplash.jpg');">
  <div class="container">
    <div class="show-category-title">
      <div class="title-bg text-center">
        <h2>Explore Venues In <%= @trip.city.capitalize %> !</h2>
        <h4>Choose Your Preferences From Each Category</h4>
      </div>
    </div>
    <div class="show-category-card-sect">
      <div class="row">
        <% i = 0 %>
        <% @foursquare_main_categories.each_with_index do |cat, index| %>
          <div class="col-xs-12 col-lg-3">
            <div class="show-category-card">
              <div class="menu-button show-category-card-image" value="<%= index %>">
                <%= cl_image_tag(Venue::VENUE_CARD_IMAGES[index]) %>
                <div class="show-category-card-caption"><%= cat %></div>
              </div>
              <div class="menu hide-start">
                <%= simple_form_for :sub_category, remote: true, url: trip_venues_path(@trip), method: :post do |f| %>
                  <%= f.input :choices, as: :check_boxes, collection: @foursquare_sub_categories[i..i+3]%>
                  <div class="submit-category-button" value="<%= index %>">
                    <%= f.submit "Next", class: "btn home-button submit-venue-category" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <% i = i+4 %>
        <% end %>
      </div>
    </div>
  </div>
    <div class="container">
      <div class="row">
        <div class="button-to-events">
          <%= link_to trip_events_path do %>
            <div class="to-events btn home-button">CHECK OUT EVENTS  >></div>
          <% end %>
        </div>
      </div>
    </div>
</div>
<script>
  const bigButtons = document.querySelectorAll('.menu-button');
  const row_of_menus = document.querySelector('.row');
  let first_menu = row_of_menus.firstElementChild;
  first_menu= first_menu.querySelector('.menu');
  first_menu.classList.remove('hide-start');

  bigButtons.forEach((bigButton) => {
    bigButton.addEventListener('click', function(event) {
      let menu = bigButton.nextElementSibling;
      menu.classList.toggle("hide-start");
      let submit = menu.querySelector('.submit-venue-category');
      submit.addEventListener("click", function(event){
        // console.log("bigButton baby");
        // console.log(bigButton.parentNode);
        // console.log(bigButton.parentNode.parentNode.nextElementSibling.firstElementChild);
        let next_guy = bigButton.parentNode.parentNode.nextElementSibling.firstElementChild;
        let next_menu = next_guy.querySelector('.menu');
        next_menu.classList.remove('hide-start');
        menu.classList.add('hide-start');
      })
    });
  });

  let submits = document.querySelectorAll(".submit-venue-category");
  submits.forEach((submit) => {
  submit.addEventListener('click', function(event){

    // console.log(submit.parentNode.parentNode.nextElementSibling.firstElementChild);
    console.log("small button, size doesn't matter");
    // console.log(submit.parentNode.parentNode.parentNode.parentNode.parentNode.nextElementSibling.firstElementChild);
    let next_guy = submit.parentNode.parentNode.parentNode.parentNode.parentNode.nextElementSibling.firstElementChild;
    let next_menu = next_guy.querySelector('.menu');
    next_menu.classList.remove('hide-start');

    console.log(submit.parentNode.parentNode.parentNode);
    let current_menu = submit.parentNode.parentNode.parentNode;
    current_menu.classList.add('hide-start');
  });
  });
</script>

app/views/venues/index.js.erb
// const bigButtons = document.querySelectorAll('.menu-button');
//   const row_of_menus = document.querySelector('.row');
//   let first_menu = row_of_menus.firstElementChild;
//   first_menu= first_menu.querySelector('.menu');
//   first_menu.classList.remove('hide-start');

//   bigButtons.forEach((bigButton) => {
//     bigButton.addEventListener('click', function(event) {
//       let menu = bigButton.nextElementSibling;
//       menu.classList.toggle("hide-start");
//       let submit = menu.querySelector('.submit-venue-category');
//       submit.addEventListener("click", function(event){
//         // console.log("bigButton baby");
//         // console.log(bigButton.parentNode);
//         // console.log(bigButton.parentNode.parentNode.nextElementSibling.firstElementChild);
//         let next_guy = bigButton.parentNode.parentNode.nextElementSibling.firstElementChild;
//         let next_menu = next_guy.querySelector('.menu');
//         next_menu.classList.remove('hide-start');
//         menu.classList.add('hide-start');
//       })
//     });
//   });

// let submits = document.querySelectorAll(".submit-venue-category");
// submits.forEach((submit) => {
//   submit.addEventListener('click', function(event){

//     // console.log(submit.parentNode.parentNode.nextElementSibling.firstElementChild);
//     console.log("small button, size doesn't matter");
//     // console.log(submit.parentNode.parentNode.parentNode.parentNode.parentNode.nextElementSibling.firstElementChild);
//     let next_guy = submit.parentNode.parentNode.parentNode.parentNode.parentNode.nextElementSibling.firstElementChild;
//     let next_menu = next_guy.querySelector('.menu');
//     next_menu.classList.remove('hide-start');

//     console.log(submit.parentNode.parentNode.parentNode);
//     let current_menu = submit.parentNode.parentNode.parentNode;
//     current_menu.classList.add('hide-start');
//   });
// });

app/views/venues/new.html.erb
<% content_for :meta_title, "#{@trip.address}" %>
<div class="bg-image-wrapper" style="background-image:
linear-gradient(-225deg, rgba(186,210,213,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://res.cloudinary.com/druzius/image/upload/v1543828892/emanuel-hahn-200491-unsplash.jpg');">
  <div class="container">
    <div class="header">
      <div class="header text-center">
        <h1>Food type</h1>
        <h4>Type in your food type and we'll give you recommendations</h4>
        <%= simple_form_for :search, url: new_trip_venue_path, wrapper: :inline_form, html: { class: "form-inline form_full_width" }, wrapper_mappings: {
        boolean: :inline_boolean
      }, method: :get do |f| %>
          <%= f.input :food_type, wrapper_html: { class: "col-5" } %>
          <%= f.input :price, as: :radio_buttons, collection: ["$", "$$", "$$$"] %>
          <%= f.submit "Submit", class: "btn home-button" %>
        <% end %>
      </div>
    </div>
    <div class="venue-category-cards">
      <div class="row">
        <% unless @venues.nil? %>
          <% @venues.each do |venue| %>
            <div class="col-xs-12 col-sm-4">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
                <div class="card-category"><%= venue[:name] %></div>
                <div class="card-description">
                  <h2><%= venue[:address] %></h2>
                </div>
              </div>
              <div class="confirm-selection text-center">
                <%= link_to "Select", trip_venues_path(params: { venue: {name: venue[:name], location: venue[:address], trip_id: @trip.id }}), method: :post, class:"btn btn-primary" %>
                <a href="#" class="btn btn-danger">shuffle</a>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>